regular update

diff --git a/.local/bin/compandrun b/.local/bin/compandrun
--- a/.local/bin/compandrun
+++ b/.local/bin/compandrun
@@ -1,8 +1,6 @@
 #!/bin/bash
 
-if [ $# -eq 0 ] || [ -z $1 ] || [ ! -f "./$1" ]; then
-	exit 1
-fi
+[ $# -eq 0 ] || [ -z $1 ] || [ ! -f "./$1" ] && exit 1
 
 # If the given file type is not C/C++ exit
 echo "$1" | grep -Evq "\.c(pp)?$" && exit 1
@@ -15,8 +13,7 @@ echo $1 | grep -Eq "\.c$" && gcc $1 -o $bin
 echo $1 | grep -Eq "\.cpp$" && g++ $1 -o $bin
 
 # Run and time execution
-if [ ! -f "./$bin" ]; then
-	echo "Compilation failed"
+[ ! -f "./$bin" ] &&
+	echo "Compilation failed" &&
 	exit 1
-fi
 time ./$bin
