Regular update

diff --git a/.local/bin/newcproj b/.local/bin/newcproj
--- a/.local/bin/newcproj
+++ b/.local/bin/newcproj
@@ -1,63 +1,31 @@
-#!/bin/bash
+#!/bin/sh
 
-# Check project name
-if [ $# -eq 0 ] || [ -z $1 ]; then
-	echo "Project name?"
+# Arguments
+# $1 - project name
+# $2 - project path
+
+CONFIG_PATH="$XDG_CONFIG_HOME/cpp-init/"
+
+if [ -z $1 ]; then
+	printf "\033[1;31m✘  \033[0mYou haven't specified the project's name!\n"
 	exit 1
 fi
 
-LANG="cpp"
-
-# Select language if present
-if [ $# -eq 2 ] || [ ! -z $2 ]; then
-	echo $2 | grep -Eoq "c(pp)?" && LANG=$2
+PROJECT_ROOT="$(pwd)/$1"
+if [ ! -z $2 ] && [ -d $2 ]; then
+	PROJECT_ROOT="$2"
 fi
 
-PROJ_PATH="$HOME/proj/c/$1"
+mkdir -p "$PROJECT_ROOT" "$PROJECT_ROOT/src" "$PROJECT_ROOT/include" "$PROJECT_ROOT/build"
 
-# Check if project already exists in order to not ovveride existing files
-if [ -d $PROJ_PATH ]; then
-	existing_file="$(ls $PROJ_PATH | grep -Eo "main\.c(pp)?")"
-	notify-send "Project already exists" "Editing existing file $existing_file"
-	
-	cd $PROJ_PATH
-	vim $PROJ_PATH/$existing_file
-	exit 1;
+if [ -f "$PROJECT_ROOT/src/$1.cpp" ] || [ -f "$PROJECT_ROOT/CMakeLists.txt" ]; then
+	printf "\033[1;31m✘  \033[0mProject files already exist! Aborting...\n"
+	exit 1
 fi
 
-# Create project files
-mkdir -p $PROJ_PATH
+echo "// Project generated by $(whoami) at $(date)" >>"$PROJECT_ROOT/src/$1.cpp"
+cat "$CONFIG_PATH/template-source.cpp" >>"$PROJECT_ROOT/src/$1.cpp"
+cp "$CONFIG_PATH/template-cmakelists.txt" "$PROJECT_ROOT/CMakeLists.txt"
+sed -i "s/TEMPLATE_PROJECT_NAME/$1/g" "$PROJECT_ROOT/CMakeLists.txt"
 
-# Create main C/C++ file
-case $LANG in
-	"cpp")
-		echo "// Project generated by $(whoami) at $(date)
-#include <bits/stdc++.h>
-
-std::ifstream in(\"$1.in\");
-std::ofstream out(\"$1.out\");
-
-int main() {
-
-	return 0;
-}
-" > "$PROJ_PATH/main.cpp"
-		touch "$PROJ_PATH/$1.in" "$PROJ_PATH/$1.out"
-		;;
-	"c")
-		echo "// Project generated by $(whoami) at $(date)
-#include <stdio.h> 
-
-int main() {
-
-	return 0;
-}
-" > "$PROJ_PATH/main.c"
-		;;
-esac
-
-# Change current directory
-cd $PROJ_PATH
-
-# Enter vim
-vim "$PROJ_PATH/main.$LANG"
+printf "\033[1;36m  Successfully created project root and initialised files for $1!\033[0m\n"
